//存放网络的宏
#ifndef CNETCOMMON_H
#define CNETCOMMON_H
#define NET_HEAD_COMMAND1 0xDD
#define NET_HEAD_COMMAND2 0xBB
#define NET_HEAD_COMMAND3 0xAA
#define NET_TAIL_COMMAND1 0xEE
#define NET_TAIL_COMMAND2 0xBB
#define NET_TAIL_COMMAND3 0xAA
#define NET_MIN_PACKET_LENGTH 3+4+2+4+0+3





#endif // CNETCOMMON_H
